
package grade.program;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * Program #2 Grade Program
 * @author Allie Bacholl
 */
public class GradeUI extends javax.swing.JFrame {

    /* Lists to store all grades */
    ArrayList progList = new ArrayList();
    ArrayList artList = new ArrayList();
    ArrayList scienceList = new ArrayList();
    ArrayList mathList = new ArrayList();   
    ArrayList historyList = new ArrayList();
    
    /**
     * Creates new form GradeUI
     */
    public GradeUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblEnterScore = new javax.swing.JLabel();
        lblProgrammingTitle = new javax.swing.JLabel();
        lblArtTitle = new javax.swing.JLabel();
        lblScienceTitle = new javax.swing.JLabel();
        lblMathTitle = new javax.swing.JLabel();
        lblHistoryTitle = new javax.swing.JLabel();
        txtFieldProg = new javax.swing.JTextField();
        txtFieldArt = new javax.swing.JTextField();
        txtFieldScience = new javax.swing.JTextField();
        txtFieldMath = new javax.swing.JTextField();
        txtFieldHistory = new javax.swing.JTextField();
        panelProgramming = new javax.swing.JTabbedPane();
        panelArt = new javax.swing.JPanel();
        lblNumberOfScoresTitleArt = new javax.swing.JLabel();
        lblCurrentAverageTitleArt = new javax.swing.JLabel();
        lblHighScoreTitleArt = new javax.swing.JLabel();
        lblLowScoreTitleArt = new javax.swing.JLabel();
        lblNumberOfScoresArt = new javax.swing.JLabel();
        lblCurrentAverageArt = new javax.swing.JLabel();
        lblHighScoreArt = new javax.swing.JLabel();
        lblLowScoreArt = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblNumberOfScoresTitleProg = new javax.swing.JLabel();
        lblCurrentAverageTitleProg = new javax.swing.JLabel();
        lblHighScoreTitleProg = new javax.swing.JLabel();
        lblLowScoreTitleProg = new javax.swing.JLabel();
        lblNumberOfScoresProg = new javax.swing.JLabel();
        lblCurrentAverageProg = new javax.swing.JLabel();
        lblHighScoreProg = new javax.swing.JLabel();
        lblLowScoreProg = new javax.swing.JLabel();
        panelScience = new javax.swing.JPanel();
        lblNumberOfScoresTitleScience = new javax.swing.JLabel();
        lblCurrentAverageTitleScience = new javax.swing.JLabel();
        lblHighScoreTitleScience = new javax.swing.JLabel();
        lblLowScoreTitleScience = new javax.swing.JLabel();
        lblNumberOfScoresScience = new javax.swing.JLabel();
        lblCurrentAverageScience = new javax.swing.JLabel();
        lblHighScoreScience = new javax.swing.JLabel();
        lblLowScoreScience = new javax.swing.JLabel();
        panelMath = new javax.swing.JPanel();
        lblNumberOfScoresTitleMath = new javax.swing.JLabel();
        lblCurrentAverageTitleMath = new javax.swing.JLabel();
        lblHighScoreTitleMath = new javax.swing.JLabel();
        lblLowScoreTitleMath = new javax.swing.JLabel();
        lblNumberOfScoresMath = new javax.swing.JLabel();
        lblCurrentAverageMath = new javax.swing.JLabel();
        lblHighScoreMath = new javax.swing.JLabel();
        lblLowScoreMath = new javax.swing.JLabel();
        panelHistory = new javax.swing.JPanel();
        lblNumberOfScoresTitleHistory = new javax.swing.JLabel();
        lblCurrentAverageTitleHistory = new javax.swing.JLabel();
        lblHighScoreTitleHistory = new javax.swing.JLabel();
        lblLowScoreTitleHistory = new javax.swing.JLabel();
        lblNumberOfScoresHistory = new javax.swing.JLabel();
        lblCurrentAverageHistory = new javax.swing.JLabel();
        lblHighScoreHistory = new javax.swing.JLabel();
        lblLowScoreHistory = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitle.setText("Grades");

        lblEnterScore.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEnterScore.setText("Enter Scores");

        lblProgrammingTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblProgrammingTitle.setText("Programming");

        lblArtTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblArtTitle.setText("Art");

        lblScienceTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblScienceTitle.setText("Science");

        lblMathTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMathTitle.setText("Math");

        lblHistoryTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHistoryTitle.setText("History");

        panelProgramming.setBackground(new java.awt.Color(255, 255, 255));

        panelArt.setBackground(new java.awt.Color(255, 255, 255));

        lblNumberOfScoresTitleArt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNumberOfScoresTitleArt.setText("Number of Scores:");

        lblCurrentAverageTitleArt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCurrentAverageTitleArt.setText("Current Average:");

        lblHighScoreTitleArt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHighScoreTitleArt.setText("High Score:");

        lblLowScoreTitleArt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLowScoreTitleArt.setText("Low Score:");

        lblNumberOfScoresArt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNumberOfScoresArt.setText("0");

        lblCurrentAverageArt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCurrentAverageArt.setText("0");

        lblHighScoreArt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHighScoreArt.setText("0");

        lblLowScoreArt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLowScoreArt.setText("0");

        javax.swing.GroupLayout panelArtLayout = new javax.swing.GroupLayout(panelArt);
        panelArt.setLayout(panelArtLayout);
        panelArtLayout.setHorizontalGroup(
            panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumberOfScoresTitleArt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCurrentAverageTitleArt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHighScoreTitleArt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLowScoreTitleArt, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumberOfScoresArt)
                    .addComponent(lblCurrentAverageArt)
                    .addComponent(lblHighScoreArt)
                    .addComponent(lblLowScoreArt))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        panelArtLayout.setVerticalGroup(
            panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelArtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblNumberOfScoresTitleArt)
                    .addComponent(lblNumberOfScoresArt))
                .addGap(18, 18, 18)
                .addGroup(panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCurrentAverageTitleArt)
                    .addComponent(lblCurrentAverageArt))
                .addGap(18, 18, 18)
                .addGroup(panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblHighScoreTitleArt)
                    .addComponent(lblHighScoreArt))
                .addGap(18, 18, 18)
                .addGroup(panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblLowScoreTitleArt)
                    .addComponent(lblLowScoreArt))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        panelProgramming.addTab("Art", panelArt);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblNumberOfScoresTitleProg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNumberOfScoresTitleProg.setText("Number of Scores:");

        lblCurrentAverageTitleProg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCurrentAverageTitleProg.setText("Current Average:");

        lblHighScoreTitleProg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHighScoreTitleProg.setText("High Score:");

        lblLowScoreTitleProg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLowScoreTitleProg.setText("Low Score:");

        lblNumberOfScoresProg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNumberOfScoresProg.setText("0");

        lblCurrentAverageProg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCurrentAverageProg.setText("0");

        lblHighScoreProg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHighScoreProg.setText("0");

        lblLowScoreProg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLowScoreProg.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLowScoreTitleProg)
                    .addComponent(lblHighScoreTitleProg)
                    .addComponent(lblCurrentAverageTitleProg)
                    .addComponent(lblNumberOfScoresTitleProg))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumberOfScoresProg)
                    .addComponent(lblCurrentAverageProg)
                    .addComponent(lblHighScoreProg)
                    .addComponent(lblLowScoreProg))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNumberOfScoresProg)
                        .addGap(18, 18, 18)
                        .addComponent(lblCurrentAverageProg)
                        .addGap(18, 18, 18)
                        .addComponent(lblHighScoreProg)
                        .addGap(18, 18, 18)
                        .addComponent(lblLowScoreProg))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNumberOfScoresTitleProg)
                        .addGap(18, 18, 18)
                        .addComponent(lblCurrentAverageTitleProg)
                        .addGap(18, 18, 18)
                        .addComponent(lblHighScoreTitleProg)
                        .addGap(18, 18, 18)
                        .addComponent(lblLowScoreTitleProg)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelProgramming.addTab("Programming", jPanel1);

        panelScience.setBackground(new java.awt.Color(255, 255, 255));

        lblNumberOfScoresTitleScience.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNumberOfScoresTitleScience.setText("Number of Scores:");

        lblCurrentAverageTitleScience.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCurrentAverageTitleScience.setText("Current Average:");

        lblHighScoreTitleScience.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHighScoreTitleScience.setText("High Score:");

        lblLowScoreTitleScience.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLowScoreTitleScience.setText("Low Score:");

        lblNumberOfScoresScience.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNumberOfScoresScience.setText("0");

        lblCurrentAverageScience.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCurrentAverageScience.setText("0");

        lblHighScoreScience.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHighScoreScience.setText("0");

        lblLowScoreScience.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLowScoreScience.setText("0");

        javax.swing.GroupLayout panelScienceLayout = new javax.swing.GroupLayout(panelScience);
        panelScience.setLayout(panelScienceLayout);
        panelScienceLayout.setHorizontalGroup(
            panelScienceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScienceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelScienceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLowScoreTitleScience)
                    .addComponent(lblHighScoreTitleScience)
                    .addComponent(lblCurrentAverageTitleScience)
                    .addComponent(lblNumberOfScoresTitleScience))
                .addGap(18, 18, 18)
                .addGroup(panelScienceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumberOfScoresScience)
                    .addComponent(lblCurrentAverageScience)
                    .addComponent(lblHighScoreScience)
                    .addComponent(lblLowScoreScience))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        panelScienceLayout.setVerticalGroup(
            panelScienceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScienceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelScienceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelScienceLayout.createSequentialGroup()
                        .addComponent(lblNumberOfScoresScience)
                        .addGap(18, 18, 18)
                        .addComponent(lblCurrentAverageScience)
                        .addGap(18, 18, 18)
                        .addComponent(lblHighScoreScience)
                        .addGap(18, 18, 18)
                        .addComponent(lblLowScoreScience))
                    .addGroup(panelScienceLayout.createSequentialGroup()
                        .addComponent(lblNumberOfScoresTitleScience)
                        .addGap(18, 18, 18)
                        .addComponent(lblCurrentAverageTitleScience)
                        .addGap(18, 18, 18)
                        .addComponent(lblHighScoreTitleScience)
                        .addGap(18, 18, 18)
                        .addComponent(lblLowScoreTitleScience)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelProgramming.addTab("Science", panelScience);

        panelMath.setBackground(new java.awt.Color(255, 255, 255));

        lblNumberOfScoresTitleMath.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNumberOfScoresTitleMath.setText("Number of Scores:");

        lblCurrentAverageTitleMath.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCurrentAverageTitleMath.setText("Current Average:");

        lblHighScoreTitleMath.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHighScoreTitleMath.setText("High Score:");

        lblLowScoreTitleMath.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLowScoreTitleMath.setText("Low Score:");

        lblNumberOfScoresMath.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNumberOfScoresMath.setText("0");

        lblCurrentAverageMath.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCurrentAverageMath.setText("0");

        lblHighScoreMath.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHighScoreMath.setText("0");

        lblLowScoreMath.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLowScoreMath.setText("0");

        javax.swing.GroupLayout panelMathLayout = new javax.swing.GroupLayout(panelMath);
        panelMath.setLayout(panelMathLayout);
        panelMathLayout.setHorizontalGroup(
            panelMathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMathLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLowScoreTitleMath)
                    .addComponent(lblHighScoreTitleMath)
                    .addComponent(lblCurrentAverageTitleMath)
                    .addComponent(lblNumberOfScoresTitleMath))
                .addGap(18, 18, 18)
                .addGroup(panelMathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumberOfScoresMath)
                    .addComponent(lblCurrentAverageMath)
                    .addComponent(lblHighScoreMath)
                    .addComponent(lblLowScoreMath))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        panelMathLayout.setVerticalGroup(
            panelMathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMathLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelMathLayout.createSequentialGroup()
                        .addComponent(lblNumberOfScoresMath)
                        .addGap(18, 18, 18)
                        .addComponent(lblCurrentAverageMath)
                        .addGap(18, 18, 18)
                        .addComponent(lblHighScoreMath)
                        .addGap(18, 18, 18)
                        .addComponent(lblLowScoreMath))
                    .addGroup(panelMathLayout.createSequentialGroup()
                        .addComponent(lblNumberOfScoresTitleMath)
                        .addGap(18, 18, 18)
                        .addComponent(lblCurrentAverageTitleMath)
                        .addGap(18, 18, 18)
                        .addComponent(lblHighScoreTitleMath)
                        .addGap(18, 18, 18)
                        .addComponent(lblLowScoreTitleMath)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelProgramming.addTab("Math", panelMath);

        panelHistory.setBackground(new java.awt.Color(255, 255, 255));

        lblNumberOfScoresTitleHistory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNumberOfScoresTitleHistory.setText("Number of Scores:");

        lblCurrentAverageTitleHistory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCurrentAverageTitleHistory.setText("Current Average:");

        lblHighScoreTitleHistory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHighScoreTitleHistory.setText("High Score:");

        lblLowScoreTitleHistory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLowScoreTitleHistory.setText("Low Score:");

        lblNumberOfScoresHistory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNumberOfScoresHistory.setText("0");

        lblCurrentAverageHistory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCurrentAverageHistory.setText("0");

        lblHighScoreHistory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHighScoreHistory.setText("0");

        lblLowScoreHistory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLowScoreHistory.setText("0");

        javax.swing.GroupLayout panelHistoryLayout = new javax.swing.GroupLayout(panelHistory);
        panelHistory.setLayout(panelHistoryLayout);
        panelHistoryLayout.setHorizontalGroup(
            panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLowScoreTitleHistory)
                    .addComponent(lblHighScoreTitleHistory)
                    .addComponent(lblCurrentAverageTitleHistory)
                    .addComponent(lblNumberOfScoresTitleHistory))
                .addGap(18, 18, 18)
                .addGroup(panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumberOfScoresHistory)
                    .addComponent(lblCurrentAverageHistory)
                    .addComponent(lblHighScoreHistory)
                    .addComponent(lblLowScoreHistory))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        panelHistoryLayout.setVerticalGroup(
            panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumberOfScoresTitleHistory)
                    .addComponent(lblNumberOfScoresHistory))
                .addGap(18, 18, 18)
                .addGroup(panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentAverageTitleHistory)
                    .addComponent(lblCurrentAverageHistory))
                .addGap(18, 18, 18)
                .addGroup(panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHighScoreTitleHistory)
                    .addComponent(lblHighScoreHistory))
                .addGap(18, 18, 18)
                .addGroup(panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLowScoreTitleHistory)
                    .addComponent(lblLowScoreHistory))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelProgramming.addTab("History", panelHistory);

        btnCalculate.setText("Calculate");
        btnCalculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalculateMouseClicked(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnCalculate)
                .addGap(18, 18, 18)
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProgrammingTitle, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblArtTitle, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblScienceTitle, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMathTitle, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblHistoryTitle, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(txtFieldProg)
                                    .addComponent(txtFieldArt)
                                    .addComponent(txtFieldScience)
                                    .addComponent(txtFieldMath)
                                    .addComponent(txtFieldHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEnterScore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(panelProgramming, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(22, 22, 22)
                        .addComponent(lblEnterScore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProgrammingTitle)
                            .addComponent(txtFieldProg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblArtTitle)
                            .addComponent(txtFieldArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblScienceTitle)
                            .addComponent(txtFieldScience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMathTitle)
                            .addComponent(txtFieldMath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHistoryTitle)
                            .addComponent(txtFieldHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelProgramming, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculate)
                    .addComponent(btnClear)
                    .addComponent(btnExit))
                .addGap(22, 22, 22))
        );

        panelProgramming.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Calculates the grades and updates the class tabs
     * @param evt Mouse click
     */
    private void btnCalculateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalculateMouseClicked
        
        Calculator gradeCalculator = new Calculator();
        
        try {
            int progGrade = gradeCalculator.verifyGrade(txtFieldProg.getText());
            int artGrade = gradeCalculator.verifyGrade(txtFieldArt.getText());
            int scienceGrade = gradeCalculator.verifyGrade(txtFieldScience.getText());
            int mathGrade = gradeCalculator.verifyGrade(txtFieldMath.getText());
            int historyGrade = gradeCalculator.verifyGrade(txtFieldHistory.getText());
            
            progList.add(progGrade);
            artList.add(artGrade);
            scienceList.add(scienceGrade);
            mathList.add(mathGrade);
            historyList.add(historyGrade);
        }
        catch (NumberFormatException | Error e) {
            JOptionPane.showMessageDialog(null, "Input Error: Please enter an integer between 0 and 100 (inclusive) into all the text fields.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
        
        /* Sets the total number of grades */
        lblNumberOfScoresArt.setText(Integer.toString(artList.size()));
        lblNumberOfScoresProg.setText(Integer.toString(progList.size()));
        lblNumberOfScoresMath.setText(Integer.toString(mathList.size()));
        lblNumberOfScoresScience.setText(Integer.toString(scienceList.size()));
        lblNumberOfScoresHistory.setText(Integer.toString(historyList.size()));
        
        /* Sets the grade averages */
        lblCurrentAverageArt.setText(Integer.toString(gradeCalculator.calcAverage(artList)));
        lblCurrentAverageProg.setText(Integer.toString(gradeCalculator.calcAverage(progList)));
        lblCurrentAverageMath.setText(Integer.toString(gradeCalculator.calcAverage(mathList)));
        lblCurrentAverageScience.setText(Integer.toString(gradeCalculator.calcAverage(scienceList)));
        lblCurrentAverageHistory.setText(Integer.toString(gradeCalculator.calcAverage(historyList)));
        
        /* Sets the grade highs */
        lblHighScoreArt.setText(Integer.toString(gradeCalculator.calcHigh(artList)));
        lblHighScoreProg.setText(Integer.toString(gradeCalculator.calcHigh(progList)));
        lblHighScoreMath.setText(Integer.toString(gradeCalculator.calcHigh(mathList)));
        lblHighScoreScience.setText(Integer.toString(gradeCalculator.calcHigh(scienceList)));
        lblHighScoreHistory.setText(Integer.toString(gradeCalculator.calcHigh(historyList)));
        
        /* Sets the grade lows */
        lblLowScoreArt.setText(Integer.toString(gradeCalculator.calcLow(artList)));
        lblLowScoreProg.setText(Integer.toString(gradeCalculator.calcLow(progList)));
        lblLowScoreMath.setText(Integer.toString(gradeCalculator.calcLow(mathList)));
        lblLowScoreScience.setText(Integer.toString(gradeCalculator.calcLow(scienceList)));
        lblLowScoreHistory.setText(Integer.toString(gradeCalculator.calcLow(historyList)));
    }//GEN-LAST:event_btnCalculateMouseClicked

    /**
     * Clears the text fields
     * @param evt Mouse Click
     */
    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        txtFieldProg.setText("");
        txtFieldArt.setText("");
        txtFieldScience.setText("");
        txtFieldMath.setText("");
        txtFieldHistory.setText("");
    }//GEN-LAST:event_btnClearMouseClicked

    /**
     * Exits the Program
     * @param evt Mouse click
     */
    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradeUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblArtTitle;
    private javax.swing.JLabel lblCurrentAverageArt;
    private javax.swing.JLabel lblCurrentAverageHistory;
    private javax.swing.JLabel lblCurrentAverageMath;
    private javax.swing.JLabel lblCurrentAverageProg;
    private javax.swing.JLabel lblCurrentAverageScience;
    private javax.swing.JLabel lblCurrentAverageTitleArt;
    private javax.swing.JLabel lblCurrentAverageTitleHistory;
    private javax.swing.JLabel lblCurrentAverageTitleMath;
    private javax.swing.JLabel lblCurrentAverageTitleProg;
    private javax.swing.JLabel lblCurrentAverageTitleScience;
    private javax.swing.JLabel lblEnterScore;
    private javax.swing.JLabel lblHighScoreArt;
    private javax.swing.JLabel lblHighScoreHistory;
    private javax.swing.JLabel lblHighScoreMath;
    private javax.swing.JLabel lblHighScoreProg;
    private javax.swing.JLabel lblHighScoreScience;
    private javax.swing.JLabel lblHighScoreTitleArt;
    private javax.swing.JLabel lblHighScoreTitleHistory;
    private javax.swing.JLabel lblHighScoreTitleMath;
    private javax.swing.JLabel lblHighScoreTitleProg;
    private javax.swing.JLabel lblHighScoreTitleScience;
    private javax.swing.JLabel lblHistoryTitle;
    private javax.swing.JLabel lblLowScoreArt;
    private javax.swing.JLabel lblLowScoreHistory;
    private javax.swing.JLabel lblLowScoreMath;
    private javax.swing.JLabel lblLowScoreProg;
    private javax.swing.JLabel lblLowScoreScience;
    private javax.swing.JLabel lblLowScoreTitleArt;
    private javax.swing.JLabel lblLowScoreTitleHistory;
    private javax.swing.JLabel lblLowScoreTitleMath;
    private javax.swing.JLabel lblLowScoreTitleProg;
    private javax.swing.JLabel lblLowScoreTitleScience;
    private javax.swing.JLabel lblMathTitle;
    private javax.swing.JLabel lblNumberOfScoresArt;
    private javax.swing.JLabel lblNumberOfScoresHistory;
    private javax.swing.JLabel lblNumberOfScoresMath;
    private javax.swing.JLabel lblNumberOfScoresProg;
    private javax.swing.JLabel lblNumberOfScoresScience;
    private javax.swing.JLabel lblNumberOfScoresTitleArt;
    private javax.swing.JLabel lblNumberOfScoresTitleHistory;
    private javax.swing.JLabel lblNumberOfScoresTitleMath;
    private javax.swing.JLabel lblNumberOfScoresTitleProg;
    private javax.swing.JLabel lblNumberOfScoresTitleScience;
    private javax.swing.JLabel lblProgrammingTitle;
    private javax.swing.JLabel lblScienceTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelArt;
    private javax.swing.JPanel panelHistory;
    private javax.swing.JPanel panelMath;
    private javax.swing.JTabbedPane panelProgramming;
    private javax.swing.JPanel panelScience;
    private javax.swing.JTextField txtFieldArt;
    private javax.swing.JTextField txtFieldHistory;
    private javax.swing.JTextField txtFieldMath;
    private javax.swing.JTextField txtFieldProg;
    private javax.swing.JTextField txtFieldScience;
    // End of variables declaration//GEN-END:variables
}
